package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public final class DrlLogger implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private DrlLogger() {
	}

	protected static org.slf4j.Logger getLogger(
			final org.kie.api.runtime.rule.RuleContext drools) {
		final String category = drools.getRule().getPackageName() + "."
				+ drools.getRule().getName();
		final org.slf4j.Logger logger = org.slf4j.LoggerFactory
				.getLogger(category);
		return logger;
	}

	public static void info(final org.kie.api.runtime.rule.RuleContext drools,
			final String message, final Object... parameters) {
		final org.slf4j.Logger logger = getLogger(drools);
		logger.info(message, parameters);
	}

	public static void debug(final org.kie.api.runtime.rule.RuleContext drools,
			final String message, final Object... parameters) {
		final org.slf4j.Logger logger = getLogger(drools);
		logger.debug(message, parameters);
	}

	public static void error(final org.kie.api.runtime.rule.RuleContext drools,
			final String message, final Object... parameters) {
		final org.slf4j.Logger logger = getLogger(drools);
		logger.error(message, parameters);
	}

}